---
- name: "{{ common_task_name_var_get }}"
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: "{{ common_task_name_pip_install }}"
  pip:
    name: "{{ item.install_list }}"
    executable: /usr/bin/pip3
  with_items:
    - "{{ pip_base }}"